### PR TITLE
DISTMYSQL-243 - Orchestrator uses inefficient subquery in REPLACE to …

### PR DESCRIPTION
**Pull request by satya-bodapati**
…update cluster aliases

Problem:
--------
Orchestrator has backend table cluster_alias to store aliases. At certain intervals, orchestrator will update the aliases or insert new host aliases. To do this, it uses the below query in UpdateClusterAliases():
```
			replace into
					cluster_alias (alias, cluster_name, last_registered)
				select
				    suggested_cluster_alias,
						cluster_name,
						now()
					from
				    database_instance
				    left join database_instance_downtime using (hostname, port)
				  where
				    suggested_cluster_alias!=''
						/* exclude newly demoted, downtimed masters */
						and ifnull(
								database_instance_downtime.downtime_active = 1
								and database_instance_downtime.end_timestamp > now()
								and database_instance_downtime.reason = ?
							, 0) = 0
					order by
						ifnull(last_checked <= last_seen, 0) asc,
						read_only desc,
						num_slave_hosts asc

```

The problem with the select query is, it will generate the duplicate records. Note that the "order" of records is important to determine the active nodes and the alias should only be updated to active nodes.

REPLACE does this operation by doing DELETE+INSERT. REPLACE repeatedly does the same work for all the duplicated records.

This creates un-necessary work for two sub systems in InnoDB
1. Purge
2. SELECTS (ReadView)

All those delete marked records create stress on Purge. SELECTs, when they have to build a older version of record, they have to build a long chain of old version records (using undo log). So the un-necessary REPLACE work will create a long chain of records to be built.

Fix:
----
Since the order is important, we cannot use "GROUP BY" to remove duplicates. Use Insert On Duplicate Key Update (IODKU) instead of REPLACE as it generates less work for InnoDB

IODKU:
------

```
INSERT INTO cluster_alias(alias, cluster_name, last_registered)
SELECT di.suggested_cluster_alias,
       di.cluster_name,
       now()
FROM   database_instance di
       LEFT JOIN database_instance_downtime did USING (hostname, port)
WHERE  di.suggested_cluster_alias != ''
       AND Ifnull(did.downtime_active = 1
                  AND did.end_timestamp > Now()
                  AND did.reason = 'lost-in-recovery', 0)
           = 0
ORDER  BY Ifnull(di.last_checked <= di.last_seen, 0) ASC,
          di.read_only DESC,
          di.num_slave_hosts ASC
ON DUPLICATE KEY UPDATE
alias = di.suggested_cluster_alias,
cluster_name = di.cluster_name,
last_registered = now();
```

Sample Performance numbers:
----------------------------
REPLACE:

Query OK, 14880 rows affected (16.93 sec)
Records: 7440  Duplicates: 7440  Warnings: 0

IODKU:

Query OK, 468 rows affected (6.17 sec)
Records: 7440  Duplicates: 234  Warnings: 0

Observe the number of records affected,number of duplicates affected and the time. IODKU is way better.

Related issue: https://github.com/openark/orchestrator/issues/0123456789

### Description

This PR [briefly explain what is does]

### CODE REVIEW

**Review by kamil-holubicki — COMMENTED** [review]
Looks fine, however I wonder if we can hit this case:
[LINK](https://dev.mysql.com/doc/refman/8.0/en/insert-on-duplicate.html#:~:text=If%20column%20b%20is%20also%20unique%2C%20the%20INSERT%20is%20equivalent%20to%20this%20UPDATE%20statement%20instead%3A)

```
> create table t1 (a int primary key, b int, unique key (b));
> insert into t1 values (0, 1);
> insert into t1 values (1, 2);
> replace into t1 values (0, 2);
Query OK, 3 rows affected (0,01 sec)
> select * from t1;
+---+------+
| a | b    |
+---+------+
| 0 |    2 |
+---+------+
1 row in set (0,00 sec)
```
vs.
```
> create table t1 (a int primary key, b int, unique key (b));
> insert into t1 values (0, 1);
> insert into t1 values (1, 2);
> insert into t1 values (0, 2) on duplicate key update a=0, b=2;
ERROR 1062 (23000): Duplicate entry '2' for key 't1.b'
```

**Comment by satya-bodapati** [comment]
> Looks fine, however I wonder if we can hit this case: [LINK](https://dev.mysql.com/doc/refman/8.0/en/insert-on-duplicate.html#:~:text=If%20column%20b%20is%20also%20unique%2C%20the%20INSERT%20is%20equivalent%20to%20this%20UPDATE%20statement%20instead%3A)
> 
> ```
> > create table t1 (a int primary key, b int, unique key (b));
> > insert into t1 values (0, 1);
> > insert into t1 values (1, 2);
> > replace into t1 values (0, 2);
> Query OK, 3 rows affected (0,01 sec)
> > select * from t1;
> +---+------+
> | a | b    |
> +---+------+
> | 0 |    2 |
> +---+------+
> 1 row in set (0,00 sec)
> ```
> 
> vs.
> 
> ```
> > create table t1 (a int primary key, b int, unique key (b));
> > insert into t1 values (0, 1);
> > insert into t1 values (1, 2);
> > insert into t1 values (0, 2) on duplicate key update a=0, b=2;
> ERROR 1062 (23000): Duplicate entry '2' for key 't1.b'
> ```

on duplicate key, you are updating the "key" again. Recommended usage is to update the non-key fields.

**Comment by satya-bodapati** [comment]
> 
@kamil-holubicki 

Its a good question.  Do you know how datbase_instance table entries are added/updated?
If this table can be updated directly with a conflicting alias name, then its possible.

Lets say we currently have 
a1host.com, a1, timestamp
a2host.com,a2, timestamp

and if database_instance has an entry like a1host.com, **a2**, timestamp, other fields.. then we will try to insert this record to cluster_alias and it could fail with dup key error.

**Comment by kamil-holubicki** [comment]
@satya-bodapati As we discussed on Slack, let's play safe and implement the fallback to the original implementation.

**Comment by satya-bodapati** [comment]
> @satya-bodapati As we discussed on Slack, let's play safe and implement the fallback to the original implementation.

@ kamil-holubicki, there is no generic/way to check for dupkey error. I am also verifying if there can be multiple backend DBs like PostgresQL or SQLLite. https://github.com/go-gorm/gorm/issues/4037

Regarding the dup key error, it shouldn't be possible by design because of the UNIQUE KEY on cluster_alias, cluster_name. We can ignore the fallback to REPLACE. One question remains though.

IODKU is MySQL specific extension and does orchestrator support multiple backends. If it does so, we somehow have to detect the backend DB is MySQL and do this change only for MySQL database backend.

**Comment by kamil-holubicki** [comment]
@satya-bodapati It supports MySql and SQLite
https://github.com/openark/orchestrator/blob/master/docs/configuration-backend.md

**Comment by satya-bodapati** [comment]
Right @kamil-holubicki I have to add an if clause and make this change for MySQL backend DB.

**Comment by satya-bodapati** [comment]
Right @kamil-holubicki I have to add an if clause and make this change for MySQL backend DB.

**Comment by satya-bodapati** [comment]
@kamil-holubicki Updated the patch with a conditional check based on backend DBs.

**Review by kamil-holubicki — APPROVED** [review]

**Comment by satya-bodapati** [comment]
https://ps80.cd.percona.com/job/mysql-orchestrator-pipeline/2/consoleFull

**Pull request merged**
